BLOCKSIZE = 20
SCREEN_WIDTH = BLOCKSIZE * 30
SCREEN_HEIGHT = BLOCKSIZE * 30
SIZESCREEN = SCREEN_WIDTH, SCREEN_HEIGHT

GAMESURF = BLOCKSIZE * 28, BLOCKSIZE * 28
TOPLEFT_GAMESURF = BLOCKSIZE, BLOCKSIZE
